// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/ozgurkadarozgur/gocommerce-product-api/ent/category"
	"github.com/ozgurkadarozgur/gocommerce-product-api/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	categoryFields := schema.Category{}.Fields()
	_ = categoryFields
	// categoryDescTitle is the schema descriptor for title field.
	categoryDescTitle := categoryFields[0].Descriptor()
	// category.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	category.TitleValidator = categoryDescTitle.Validators[0].(func(string) error)
}
