// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)
